In [22]:
from keras import backend as K
from keras.models import *
from keras.layers import *
import numpy as np
import keras

In [77]:
a = np.ones((1,20))
print(a.sum())
a

20.0


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [78]:
bla = model.predict(a)
print(bla.sum())
bla

20.0


array([[[20.]]], dtype=float32)

In [79]:
a = np.arange(20).reshape(1,-1)
print(a.sum())
a

190


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [80]:
bla = model.predict(a)
print(bla.sum())
bla

190.0


array([[[190.]]], dtype=float32)

In [62]:
a.sum()

105

In [76]:


model = Sequential()
model.add(InputLayer(input_shape=(a.shape[1],)))
model.add(Lambda(lambda x: K.expand_dims(x, axis=-1)))

#model.summary()
#model.add(Lambda(lambda x: K.pool2d(x, pool_size=(2,1), strides=(2,1), pool_mode='avg', padding='valid')))

p_s = 5
model.add(AvgPool1D(pool_size=p_s, padding='valid'))
model.add(Lambda(lambda x: p_s*x)) #revert average

p_s = 4
model.add(AvgPool1D(pool_size=p_s, padding='valid'))
model.add(Lambda(lambda x: p_s*x)) #revert average

#cnn.add(Lambda(min_max_pool2d, output_shape=min_max_pool2d_output_shape))
model.summary()

Model: "sequential_33"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lambda_52 (Lambda)           (None, 20, 1)             0         
_________________________________________________________________
average_pooling1d_15 (Averag (None, 4, 1)              0         
_________________________________________________________________
lambda_53 (Lambda)           (None, 4, 1)              0         
_________________________________________________________________
average_pooling1d_16 (Averag (None, 1, 1)              0         
_________________________________________________________________
lambda_54 (Lambda)           (None, 1, 1)              0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [24]:
#self.pool_size = conv_utils.normalize_tuple(pool_size, 1, 'pool_size')
keras.utils.conv_utils.normalize_tuple(2, 1, 'strides')

(2,)

In [26]:
keras.utils.conv_utils.normalize_tuple(2, 1, 'pool_size')

(2,)

In [28]:
K.normalize_data_format(data_format)

NameError: name 'data_format' is not defined

In [45]:
model.predict(a)

array([[[ 1.],
        [ 5.],
        [ 9.],
        [13.],
        [17.],
        [21.],
        [25.]]], dtype=float32)