# K2 Mission

Metadata documentation: https://exoplanetarchive.ipac.caltech.edu/docs/API_k2candidates_columns.html

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [1]:
!ls /work/work_teamEXOPLANET

GAF	    KOI_LC  MTF_gabo  MTF_margarita  obj4
K2_mission  MTF     MTF_gN    MTF_std	     Tass


In [2]:
!ls /work/work_teamEXOPLANET/K2_mission/

K2_CAND_dataset.csv		      K2_CAND_time.npy
k2candidates_2020.04.18_21.34.57.csv  k2names_2020.04.19_11.26.00.csv
K2_CAND_lc_detr.npy		      K2_PLANET_lc_detr.npy
K2_CAND_LC_processed.npy	      k2_planets_search.txt
K2_CAND_LC_processed_time.npy	      K2_PLANET_time.npy
K2_CAND_metadata.csv		      K_CAND_metadata.csv


In [4]:
folder = "/work/work_teamEXOPLANET/K2_mission/"

In [9]:
df_aux = pd.read_csv(folder+"k2candidates_2020.04.18_21.34.57.csv")

###REMOVE DUPLICATE OBSERVATIONS ####
df_aux.drop_duplicates(subset = ["epic_candname", "pl_name"],inplace=True)

print("Data shape ",df_aux.shape)
df_aux.head()

Data shape  (1452, 147)


rowid       epic_name                  tm_name      epic_candname  \
0      1  EPIC 201092629  2MASS J12045739-0648180  EPIC 201092629.01   
1      2  EPIC 201102594  2MASS J11592060-0631042  EPIC 201102594.01   
2      3  EPIC 201110617  2MASS J12104805-0617391  EPIC 201110617.01   
4      5  EPIC 201111557  2MASS J12152316-0616056  EPIC 201111557.01   
6      7  EPIC 201126503  2MASS J11434522-0552228  EPIC 201126503.01   

    pl_name k2c_refdisp                                        k2c_reflink  \
0  K2-241 b   CONFIRMED  <a refstr=LIVINGSTON_ET_AL__2018 href=https://...   
1  K2-242 b   CONFIRMED  <a refstr=LIVINGSTON_ET_AL__2018 href=https://...   
2  K2-156 b   CONFIRMED  <a refstr=MAYO_ET_AL__2018 href=https://ui.ads...   
4       NaN   CANDIDATE  <a refstr=LIVINGSTON_ET_AL__2018 href=https://...   
6       NaN   CANDIDATE  <a refstr=VANDERBURG_ET_AL__2016 href=https://...   

    k2c_disp k2c_note  k2_campaign  ...  st_bmvjlim st_jmh2  st_jmh2err  \
0  CONFIRMED      NaN         10.0  ...         0.0   0.454       0.032   
1  CONFIRMED      NaN         10.0  ...         0.0   0.606       0.032   
2  CONFIRMED      NaN         10.0  ...         0.0   0.567       0.039   
4  CANDIDATE      NaN         10.0  ...         0.0   0.482       0.033   
6  CANDIDATE      NaN          1.0  ...         NaN   0.653       0.067   

  st_jmh2lim  st_hmk2  st_hmk2err  st_hmk2lim  st_jmk2  st_jmk2err  st_jmk2lim  
0        0.0    0.055       0.031         0.0    0.509       0.033         0.0  
1        0.0    0.238       0.034         0.0    0.844       0.033         0.0  
2        0.0    0.181       0.034         0.0    0.748       0.038         0.0  
4        0.0    0.171       0.030         0.0    0.653       0.030         0.0  
6        0.0    0.190       0.089         0.0    0.843       0.080         0.0  

[5 rows x 147 columns]

In [139]:
df_aux[df_aux["k2_campaign"] == 0.0]

rowid       epic_name                  tm_name      epic_candname  \
370    371  EPIC 202059377  2MASS J06364422+2139056  EPIC 202059377.01   
372    373  EPIC 202060800  2MASS J06102186+2347390  EPIC 202060800.01   
373    374  EPIC 202062450  2MASS J06232724+1432496  EPIC 202062450.01   
374    375  EPIC 202064253  2MASS J06060100+2253303  EPIC 202064253.01   
375    376  EPIC 202065819  2MASS J06180848+2450023  EPIC 202065819.01   
376    377  EPIC 202066192  2MASS J06205938+2607313  EPIC 202066192.01   
377    378  EPIC 202066537  2MASS J06570390+1837365  EPIC 202066537.01   
380    381  EPIC 202066811  2MASS J06532672+1649592  EPIC 202066811.01   
381    382  EPIC 202071289  2MASS J06204394+2454156  EPIC 202071289.01   
384    385  EPIC 202071401  2MASS J06413069+2055222  EPIC 202071401.01   
387    388  EPIC 202071635  2MASS J06141723+1837373  EPIC 202071635.01   
388    389  EPIC 202071645  2MASS J06310592+1742043  EPIC 202071645.01   
389    390  EPIC 202071725  2MASS J06252448+2439571  EPIC 202071725.01   
390    391  EPIC 202072596  2MASS J06380257+2056215  EPIC 202072596.01   
391    392  EPIC 202072965  2MASS J06262389+2756442  EPIC 202072965.01   
392    393  EPIC 202083828  2MASS J06164957+2435470  EPIC 202083828.01   
395    396  EPIC 202084970  2MASS J06572384+1930253  EPIC 202084970.01   
396    397  EPIC 202085553  2MASS J06413711+2412243  EPIC 202085553.01   
397    398  EPIC 202085597  2MASS J06381323+1813424  EPIC 202085597.01   
398    399  EPIC 202085698  2MASS J06153287+2724367  EPIC 202085698.01   
399    400  EPIC 202085934  2MASS J06571600+2007280  EPIC 202085934.01   
400    401  EPIC 202086291  2MASS J06174792+2536092  EPIC 202086291.01   
401    402  EPIC 202086968  2MASS J06280135+1623198  EPIC 202086968.01   
402    403  EPIC 202088212  2MASS J06223391+1444303  EPIC 202088212.01   
405    406  EPIC 202089657  2MASS J06054885+2329043  EPIC 202089657.01   
407    408  EPIC 202090152  2MASS J06441899+2806488  EPIC 202090152.01   
408    409  EPIC 202090723  2MASS J06005482+2356189  EPIC 202090723.01   
409    410  EPIC 202090737  2MASS J06395763+1710519  EPIC 202090737.01   
410    411  EPIC 202091388  2MASS J06052730+2115217  EPIC 202091388.01   
413    414  EPIC 202092480  2MASS J06521254+2520207  EPIC 202092480.01   
414    415  EPIC 202092559  2MASS J06574486+2415569  EPIC 202092559.01   
415    416  EPIC 202092782  2MASS J06102699+1651547  EPIC 202092782.01   
416    417  EPIC 202093020  2MASS J06330583+1652128  EPIC 202093020.01   
418    419  EPIC 202093968  2MASS J06243870+2107326  EPIC 202093968.01   
419    420  EPIC 202094740  2MASS J06415114+2705499  EPIC 202094740.01   
421    422  EPIC 202126847  2MASS J06484831+1709428  EPIC 202126847.01   
422    423  EPIC 202126849  2MASS J06393552+2528571  EPIC 202126849.01   
425    426  EPIC 202126852  2MASS J06432353+2715082  EPIC 202126852.01   
428    429  EPIC 202126853  2MASS J06584878+1911348  EPIC 202126853.01   
429    430  EPIC 202126884  2MASS J06264300+2512178  EPIC 202126884.01   
430    431  EPIC 202126887  2MASS J06373133+2647115  EPIC 202126887.01   
433    434  EPIC 202126888  2MASS J06321140+2713111  EPIC 202126888.01   
435    436  EPIC 202137637  2MASS J06083629+2347328  EPIC 202137637.01   
436    437  EPIC 202139294  2MASS J06102194+2726436  EPIC 202139294.01   
964    965  EPIC 207389002  2MASS J06504528+1648302  EPIC 207389002.01   
965    966  EPIC 207517400  2MASS J06223137+1720094  EPIC 207517400.01   
966    967  EPIC 207739861  2MASS J06381304+1813378  EPIC 207739861.01   
967    968  EPIC 208445756  2MASS J06230792+2058172  EPIC 208445756.01   
968    969  EPIC 208833261  2MASS J06042598+2229580  EPIC 208833261.01   
969    970  EPIC 209036259  2MASS J06273842+2320267  EPIC 209036259.01   
970    971  EPIC 209286622  2MASS J06154033+2421597  EPIC 209286622.01   

        pl_name     k2c_refdisp  \
370         NaN  FALSE POSITIVE   
372         NaN       CANDIDATE   
373         NaN       CANDIDATE   
374         NaN 

In [5]:
df_aux["k2c_refdisp"].value_counts() #lo que piensa K2

CANDIDATE         1093
FALSE POSITIVE     216
CONFIRMED          143
Name: k2c_refdisp, dtype: int64

In [6]:
df_aux["k2c_disp"].value_counts() #lo que piensa NASA (varias confirmados son confirmados por otras misiones)

CANDIDATE         888
CONFIRMED         342
FALSE POSITIVE    222
Name: k2c_disp, dtype: int64

df_aux2 = pd.read_csv(folder+"k2names_2020.04.19_11.26.00.csv")
df_aux2.drop_duplicates(subset = ["k2_name"],inplace=True)

print("Data shape ",df_aux2.shape)
df_aux2.head() ## faltan datos.. nose xke

In [6]:
lc_measurements = np.load(folder+"K2_PLANET_lc_detr.npy", allow_pickle=True)
lc_time = np.load(folder+"K2_PLANET_time.npy", allow_pickle=True)
lc_measurements

array([array([0.99992715, 0.99990222, 0.99995757, ..., 1.00028617, 1.00033756,
       1.00045506]),
       array([1.00134744, 1.00286146, 1.00136884, ..., 1.00305468, 1.00480594,
       1.00477628]),
       array([0.99991211, 0.99988666, 0.99982736, ..., 1.00049009, 1.00058772,
       1.00057912]),
       ...,
       array([0.99074986, 0.98995069, 0.98986599, ..., 0.94409265, 0.94362504,
       0.94416325]),
       list([nan]), list([nan])], dtype=object)

In [8]:
mask_downl = ~np.asarray([len(value)==1 and np.isnan(value[0]) for value in lc_time])

lc_measurements = lc_measurements[mask_downl]
lc_time = lc_time[mask_downl]

len(lc_measurements)

1442

In [12]:
## save data that were downloaded

df_aux[mask_downl].to_csv(folder+"/K2_CAND_dataset.csv",index=False)

np.save(folder+"/K2_CAND_time.npy",lc_time)
np.save(folder+"/K2_CAND_lc_detr.npy",lc_measurements)